

FROM python:3.11-slim


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


WORKDIR /app


COPY requirements.txt .



RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
        python3-dev \
        redis-tools \
    && rm -rf /var/lib/apt/lists/*


RUN pip install --upgrade pip
RUN pip install -r requirements.txt


COPY . .


RUN mkdir -p logs
















EXPOSE 8000






CMD ["sh", "-c", "uvicorn notification_gateway.asgi:application --host 0.0.0.0 --port 8000"]