"""
Django settings for notification_gateway project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/  

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/  
"""

import os
from pathlib import Path
import sys
from urllib.parse import urlparse
from decouple import config


BASE_DIR = Path(__file__).resolve().parent.parent





SECRET_KEY = config('SECRET_KEY', 'django-insecure-change-this-in-production')
INTERNAL_API_SECRET = config('INTERNAL_API_SECRET')


DEBUG = config('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = config('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'rest_framework',
    'corsheaders',
    'gateway_api',  
    'django_prometheus',
    'channels',
    'django.contrib.staticfiles',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    
    
    'gateway_api.middleware.CorrelationIdMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'notification_gateway.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'notification_gateway.wsgi.application'



if DEBUG:
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', 'gateway_api_db'),
            'USER': config('DB_USER', 'postgres'),
            'PASSWORD': config('DB_PASSWORD', 'postgres'),
            'HOST': config('DB_HOST', 'postgres'),
            'PORT': config('DB_PORT', '5432'),
            'CONN_MAX_AGE': 600,  
        }
    }


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
    'EXCEPTION_HANDLER': 'gateway_api.exceptions.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],

}


RABBITMQ_URL = config('RABBITMQ_URL')


USER_SERVICE_URL = config('USER_SERVICE_URL')
TEMPLATE_SERVICE_URL = config('TEMPLATE_SERVICE_URL', 'http://localhost:8002' if DEBUG else 'http://template-service:8000')


CORS_ALLOW_ALL_ORIGINS = True


PROMETHEUS_EXPORT_MIGRATIONS = False
METRICS_ENABLED = config('METRICS_ENABLED', 'True') == 'True'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ASGI_APPLICATION = 'notification_gateway.asgi.application'




# notification_gateway/notification_gateway/settings.py

SPECTACULAR_SETTINGS = {
    'TITLE': 'Notification Gateway API',
    'DESCRIPTION': 'API for sending and managing notifications',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    'SECURITY': [
        {'apiKey': 'X-API-Key'} 
    ],
    'SECURITY_DEFINITIONS': {
        'X-API-Key': { 
            'type': 'apiKey',
            'in': 'header',
            'name': 'X-API-Key',
            'description': 'API Key for organization-specific access'
        }
    },

    'SERVERS': [
        {'url': 'http://127.0.0.1:8000', 'description': 'Development server'},
        # {'url': 'https://api.yourdomain.com', 'description': 'Production server'},
    ],
    'SCHEMA_PATH_PREFIX': '/api/v[0-9]',
}




LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message} [correlation_id={correlation_id}]',
            'style': '{',
        },
        'simple': { 
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'correlation_id': {
            
            '()': 'gateway_api.logging_filters.CorrelationIdFilter', 
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO', 
            'class': 'logging.FileHandler', 
            'filename': 'logs/app.log', 
            'formatter': 'verbose', 
            'filters': ['correlation_id'], 
        },
        'console': { 
            'level': 'DEBUG', 
            'class': 'logging.StreamHandler',
            'formatter': 'simple', 
            'filters': ['correlation_id'], 
        },
    },
    'root': {
        'handlers': ['file', 'console'], 
        'level': 'INFO', 
    },
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}



redis_url = config('REDIS_URL')
REDIS_URL = redis_url
EMAIL_SERVICE_URL = config("EMAIL_SERVICE_URL")
PUSH_SERVICE_URL = config('PUSH_SERVICE_URL')