# Generated by Django 4.2.7 on 2025-11-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('plan', models.CharField(choices=[('pro', 'Pro'), ('enterprise', 'Enterprise'), ('bronze', 'Bronze'), ('platinum', 'Platinum'), ('industry', 'Industry')], max_length=50)),
                ('quota_limit', models.IntegerField(default=10000)),
                ('quota_used', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organizations',
                'indexes': [models.Index(fields=['api_key', 'is_active'], name='organizatio_api_key_7e525b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('correlation_id', models.CharField(db_index=True, max_length=36)),
                ('organization_id', models.CharField(db_index=True, max_length=36)),
                ('user_id', models.CharField(db_index=True, max_length=36)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push')], max_length=20)),
                ('template_code', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('rejected', 'Rejected')], default='queued', max_length=20)),
                ('priority', models.IntegerField(default=5)),
                ('request_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx'), models.Index(fields=['status', '-created_at'], name='notificatio_status_f96f3f_idx'), models.Index(fields=['organization_id', '-created_at'], name='notificatio_organiz_9ef220_idx')],
            },
        ),
    ]
